- name: Install packages
  when: ( ansible_facts['distribution'] == "Amazon" or ansible_facts['distribution'] == "CentOS" )
  become: true
  become_method: sudo 
  user: ec2-user
  tasks: 
  - name: Add users
    ansible.builtin.user:
      name: "{{ item }}"
      state: present
    with_items:
    - Bob
    - ben
    - lisa
    - katty
