# ansible-playbook IAAC/vpc.yaml 
---
- name: Add ec2
  hosts: localhost
  vars_files:
    envs/dev.yaml
  tasks:
  - name: create a VPC with dedicated tenancy and a couple of tags
    amazon.aws.ec2_vpc_net:
      name: "{{ vpc_name }}"
      cidr_block: "{{ vpc_cidr_block }}"
      region: "{{ region }}"
      tags: "{{ aws_tags }}"
      tenancy: "{{ vpc_tenancy }}"
