---
# tasks file for example
- name: Install httpd and prerequisites
  when: ( ansible_facts['distribution'] == "Amazon" or ansible_facts['distribution'] == "CentOS" )
  package: 
    name: "{{ item }}" 
    state: present
  with_items:
  - httpd
  - php
  - php-mysql
  - wget 
  notify: 
  - Start web server

- name: Install mariadb
  when: ( ansible_facts['distribution'] == "Amazon" or ansible_facts['distribution'] == "CentOS" )
  package: 
    name: "{{ item }}" 
    state: present
  with_items:
  - mariadb
  notify: 
  - Start DB server

- name: Get wordpress 
  when: ( ansible_facts['distribution'] == "Amazon" or ansible_facts['distribution'] == "CentOS" )
  get_url:
    url: https://wordpress.org/wordpress-4.0.32.tar.gz
    dest: /tmp/wordpress-4.0.32.tar.gz
    mode: '0440'

- name: Extract wordpress
  when: ( ansible_facts['distribution'] == "Amazon" or ansible_facts['distribution'] == "CentOS" )
  ansible.builtin.unarchive:
    src: /tmp/wordpress-4.0.32.tar.gz
    dest: /var/www/html
    remote_src: true

- name: Host Wordpress
  when: ( ansible_facts['distribution'] == "Amazon" or ansible_facts['distribution'] == "CentOS" )
  shell: "cp -r /var/www/html/wordpress/* /var/www/html/"
  ignore_errors: true

